pipelines:
  new_pipeline:
    group: from_yaml
    materials:
      backend:
        git: https://github.com/timobartels/photowebsite.git
        branch: master
    stages:
      - first_stage:
          clean_workspace: true
          jobs:
            myjob1:
              tasks:
                - exec:
                   command: hostname
                - exec:
                   command: pwd
